const $=id=>document.getElementById(id);
let stage='blind',generation=0;
function node(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function table(head,rows){const t=node('table'),h=node('tr');head.forEach(x=>h.append(node('th',x)));t.append(h);rows.forEach(row=>{const tr=node('tr');row.forEach(v=>tr.append(node('td',String(v))));t.append(tr);});return t;}
function select(label,choices){const l=node('label',label),s=node('select');s.required=true;const blank=node('option','Choose...');blank.value='';s.append(blank);choices.forEach(v=>{const o=node('option',v);o.value=v;s.append(o);});l.append(s);return [l,s];}
function setStage(value){stage=value;generation++;$('review-content').hidden=true;$('review-content').replaceChildren();$('review-status').textContent='';['blind','resolve','metrics'].forEach(name=>$(name==='resolve'?'resolve-tab':`${name}-tab`).className=stage===name?'':'secondary');$('identity-label').hidden=stage!=='blind';$('reviewer').required=stage==='blind';$('load-button').textContent=stage==='blind'?'Load questions':stage==='resolve'?'Load reviews':'Calculate agreement';$('stage-help').textContent=stage==='blind'?'Read the policy and both answers before labeling. Model names, judge verdicts and other reviewers’ labels are hidden here. Use a consistent reviewer name; names are self-declared.':stage==='resolve'?'Your saved reviews appear below. Compare their decisions, then record one final human verdict for each answer and explain your decision. Model judgments stay hidden here.':'Agreement is calculated only for adjudicated answers from this exact experiment. It does not update past reports or approve a release.';}
function evidence(root,c){root.append(node('h2',c.question));c.evidence.forEach(e=>{root.append(node('pre',e.text));if(e.url.startsWith('https://')){const a=node('a','Policy source');a.href=e.url;a.target='_blank';a.rel='noopener noreferrer';root.append(a);}});const answers=node('div');answers.className='answers';Object.entries(c.answers).forEach(([label,text])=>{const box=node('div');box.append(node('h3',`Answer ${label}`),node('pre',text));answers.append(box);});root.append(answers);}
function formFor(root,c,actor,runId,adjudicate){
  const labels=adjudicate?['A','B']:['X','Y'],form=node('form');form.style.marginTop='20px';const fields={};
  labels.forEach(a=>{const [label,input]=select(`Answer ${a}`,['accept','reject']);fields[a]=input;form.append(label);});
  const [preferenceLabel,preference]=select('Better answer',[...labels,'tie','insufficient']);form.append(preferenceLabel);
  const reasonLabel=node('label','Reason and policy evidence');reasonLabel.style.width='100%';const reason=node('textarea');reason.required=true;reason.maxLength=4000;reasonLabel.append(reason);form.append(reasonLabel);
  let confirmation;if(!adjudicate){const l=node('label','I reviewed these answers independently without consulting model verdicts or another reviewer’s labels.');confirmation=node('input');confirmation.type='checkbox';confirmation.required=true;l.append(confirmation);form.append(l);}
  const button=node('button',adjudicate?'Save adjudication':'Save review and continue');form.append(button);root.append(form);
  form.onsubmit=async event=>{event.preventDefault();button.disabled=true;try{const body=adjudicate?{case_id:c.case_id,verdict_a:fields.A.value,verdict_b:fields.B.value,preference:preference.value,rationale:reason.value}:{reviewer:actor,case_id:c.case_id,answers_hash:c.answers_hash,verdict_x:fields.X.value,verdict_y:fields.Y.value,preference:preference.value,rationale:reason.value,independent:confirmation.checked};await api(`/api/human-review/${runId}/${adjudicate?'adjudication':'reviews'}`,body);if($('review-experiment').value===runId&&stage===(adjudicate?'resolve':'blind'))await load();}catch(e){$('review-status').textContent=e.message;button.disabled=false;}};
}
async function load(){const current=++generation,runId=$('review-experiment').value,actor=$('reviewer').value.trim(),mode=stage;const root=$('review-content');root.hidden=true;root.replaceChildren();if(!runId)return;if(mode==='blind'&&!actor){$('review-status').textContent='Enter your name or handle.';return;}$('review-status').textContent='Loading...';try{
  const url=`/api/human-review/${runId}/`+(mode==='blind'?`blind?reviewer=${encodeURIComponent(actor)}`:mode==='resolve'?'adjudication':'metrics');const data=await api(url);if(current!==generation)return;root.hidden=false;
  if(mode==='blind'){$('review-status').textContent=`${data.reviewed} of ${data.total} questions reviewed by ${actor}.`;if(!data.cases.length){root.append(node('p','No questions remain for your review.'));return;}const c=data.cases[0];evidence(root,c);const rubric=node('details');rubric.append(node('summary','Scoring rubric'));Object.entries(data.rubric).forEach(([name,scale])=>rubric.append(node('h3',name),table(['Score','Description'],Object.entries(scale))));root.append(rubric,node('p','Accept means supported, useful and safe. Reject means a material error or unsafe advice. Use insufficient when the evidence cannot establish a pairwise preference.'));formFor(root,c,actor,runId,false);}
  else if(mode==='resolve'){$('review-status').textContent=`${data.cases.length} questions ready for a final decision; ${data.resolved} finalized; ${data.awaiting_second_review} need more reviews.`;if(!data.cases.length){root.append(node('p','No questions are ready for adjudication.'));return;}const c=data.cases[0];evidence(root,c);root.append(node('h3',`${c.reviews.length} saved reviews`),node('p','Answer labels are aligned to A and B here. X and Y may have appeared in a different order for each reviewer.'),table(['Reviewer','A','B','Preference','Reason'],c.reviews.map(r=>[r.reviewer,r.verdicts.A,r.verdicts.B,r.preference,r.rationale])));root.append(node('h3','Final human decision'),node('p','The reviews above are already saved. This separate decision is the reference used to compare the AI judges.'));formFor(root,c,actor,runId,true);}
  else{$('review-status').textContent=`${data.adjudicated_cases} of ${data.total_cases} questions adjudicated.`;if(!data.adjudicated_cases){root.append(node('h2','No final human decisions yet'),node('p',`${data.reviews.length} review submissions saved for this experiment. Judge agreement uses final decisions, so there are no rates to calculate yet.`));const next=node('button','Open adjudication');next.type='button';next.onclick=()=>{setStage('resolve');load();};root.append(next);return;}const pct=x=>x===null?'No reference cases':`${(x*100).toFixed(1)}%`;root.append(node('h2','Judge agreement with human verdicts'),table(['Judge','Reviewed cases','Verdict agreement','Preference agreement','False acceptance','False rejection','Abstentions'],data.judges.map(j=>[j.judge,j.cases,pct(j.agreement),pct(j.preference_agreement),`${j.false_acceptances}/${j.unacceptable_references} (${pct(j.false_acceptance_rate)})`,`${j.false_rejections}/${j.acceptable_references} (${pct(j.false_rejection_rate)})`,j.abstentions])),node('p',data.note));const download=node('a','Download reviews, adjudications and metrics');download.download=`human-review-${runId}.json`;download.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));root.append(download);}
}catch(e){if(current===generation)$('review-status').textContent=e.message;}}
$('load-form').onsubmit=e=>{e.preventDefault();load();};$('blind-tab').onclick=()=>setStage('blind');$('resolve-tab').onclick=()=>{setStage('resolve');load();};$('metrics-tab').onclick=()=>{setStage('metrics');load();};$('review-experiment').onchange=()=>{setStage(stage);if(stage!=='blind')load();};$('reviewer').oninput=()=>{if(stage==='blind'){generation++;$('review-content').hidden=true;}};
async function init(){setStage('blind');$('review-content').style.overflowX='auto';try{const runs=(await api('/api/experiments')).filter(r=>r.state==='completed');runs.forEach(r=>{const o=node('option',`Experiment ${r.number}`);o.value=r.id;$('review-experiment').append(o);});if(!runs.length){$('review-status').textContent='Complete an experiment before reviewing.';$('load-button').disabled=true;}}catch(e){$('review-status').textContent=e.message;}}
init();
